# Generated by Django 4.0.3 on 2022-03-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='fone',
            field=models.CharField(max_length=20),
        ),
    ]
