# Generated by Django 4.0.3 on 2022-03-25 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0003_contact_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='info',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
